# Generated by Django 3.1.7 on 2021-05-17 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_list',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search_list',
            name='courseName',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
