# Generated by Django 3.1.7 on 2021-05-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210517_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search_List',
        ),
    ]
